In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [3]:
x = torch.arange(4)
torch.save(x, 'x-file')

In [5]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [6]:
y = torch.zeros(4)
torch.save([x,y], 'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [9]:
mydict = {'x':x, 'y':y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2['x'], mydict2

(tensor([0, 1, 2, 3]),
 {'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])})

In [10]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.output = nn.LazyLinear(10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

/Users/jayx/miniforge3/lib/python3.10/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [12]:
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.2159,  0.0872,  0.0975,  ...,  0.2057,  0.1578,  0.0286],
                      [-0.0805,  0.1570, -0.1246,  ..., -0.0318,  0.0363,  0.0303],
                      [ 0.0841,  0.0896,  0.1910,  ...,  0.1310,  0.1123, -0.2233],
                      ...,
                      [-0.0297,  0.0268, -0.2232,  ...,  0.1779,  0.2209, -0.0070],
                      [-0.1829, -0.1700, -0.1952,  ..., -0.1971,  0.0909,  0.2071],
                      [-0.0765,  0.0498,  0.1159,  ...,  0.0032, -0.0610, -0.0458]])),
             ('hidden.bias',
              tensor([-0.1700,  0.1111,  0.1403, -0.1061,  0.1650,  0.1942, -0.0579,  0.0213,
                      -0.0350, -0.1911, -0.0708, -0.0396, -0.0474,  0.1998,  0.1579, -0.1230,
                      -0.1582, -0.1575,  0.1851,  0.1642,  0.0698, -0.1192, -0.1635,  0.1193,
                       0.0471, -0.1660,  0.2153,  0.1845, -0.1903,  0.0669,  0.1488,  0.0753,
                      -0.1439,

In [13]:
torch.save(net.state_dict(), 'mlp.params')

In [14]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

/Users/jayx/miniforge3/lib/python3.10/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)

In [16]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])