In [1]:
import torch

In [14]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [15]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [16]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [17]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [18]:
x.grad == 4*x

tensor([True, True, True, True])

In [22]:
x.grad.zero_()
x.grad

tensor([0., 0., 0., 0.])

In [25]:
y = x.sum()
y.backward()
x.grad


tensor([3., 3., 3., 3.])

In [29]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [31]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

u

tensor([0., 1., 4., 9.])