In [1]:
import torch
import numpy as np

In [31]:
x=torch.arange(12)
x.shape

torch.Size([12])

In [54]:
y=x.reshape(3,4)

In [55]:
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [56]:
y[:,-1]

tensor([ 3,  7, 11])

In [58]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [25]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
torch.randn(3,4)

tensor([[-0.5194, -1.0696,  0.1220,  0.1084],
        [ 0.8225,  1.6739, -1.0190,  0.4098],
        [ 0.1029, -0.8653,  0.4467, -0.3770]])

In [36]:
torch.randn(12)

tensor([-2.3701,  0.0587,  0.2054, -0.6300, -1.3193, -0.1899, -0.2678, -1.4423,
        -0.4129,  0.2594, -1.1802, -0.0258])

In [39]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
# torch.tensor()
x = torch.tensor(3.0)
y = torch.tensor(4.0)
x + y, x* y, x /y, x ** y

(tensor(7.), tensor(12.), tensor(0.7500), tensor(81.))

In [22]:
# torch.reshape(), torch.arrange()
x = torch.arange(6)
A = x.reshape(2,3)
x,A

(tensor([0, 1, 2, 3, 4, 5]),
 tensor([[0, 1, 2],
         [3, 4, 5]]))

In [23]:
# len(x)
len(x), len(A),x.shape, A.shape

(6, 2, torch.Size([6]), torch.Size([2, 3]))

In [26]:
# transopse: A.T
A.T

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [31]:
# A.sum
A = torch.tensor([[1,1,1], [1,1,1]])
A.sum(axis=0), A.sum(axis=1), A.sum()

(tensor([2, 2, 2]), tensor([3, 3]), tensor(6))

In [33]:
# 非降维求和
A = torch.tensor([[1,1,1], [1,1,1]])
A.sum(axis=0, keepdim=True)

tensor([[2, 2, 2]])

In [39]:
# @
x = torch.tensor([1,1,1])
y = torch.tensor([1,1,1])
z = torch.tensor([[1,1], [1,1], [1,1]])
x @ y, x @ z

(tensor(3), tensor([3, 3]))

In [43]:
# norm
x = torch.tensor([1.,2.,3.])
torch.norm(x)

tensor(3.7417)

In [70]:
x1 = torch.randn(3,3)
x2 = torch.randn(5,3)
x = torch.cat((x1,x2),dim=0)
x

tensor([[-0.3717,  0.4916, -1.6064],
        [ 0.8738,  0.2243,  1.8659],
        [-0.4095,  0.7126,  1.2690],
        [ 1.6373, -0.2739,  0.1715],
        [-1.1964, -1.3884,  1.0263],
        [-0.0355,  0.0925,  1.5802],
        [-0.8045, -0.6203, -0.5477],
        [-1.8090,  0.3502, -1.6052]])

In [76]:
A = x.numpy()
B = torch.from_numpy(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

float