In [1]:
import torch

In [5]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [6]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [9]:
len(x)

3

In [10]:
x.shape

torch.Size([3])

In [15]:
A = torch.arange(12).reshape(3,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [16]:
A.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [18]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [23]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A, A*B, A@A.T, torch.mm(A,A.T)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]),
 tensor([[ 5., 14.],
         [14., 50.]]),
 tensor([[ 5., 14.],
         [14., 50.]]))

In [34]:
sum_A = A.sum(axis=0, keepdim=True)
sum_A

tensor([[3., 5., 7.]])

In [33]:
A/sum_A

tensor([[0.0000, 0.2000, 0.2857],
        [1.0000, 0.8000, 0.7143]])

In [37]:
A = torch.arange(10)
A.cumsum(axis=-1)

tensor([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [62]:
x = torch.ones(3)
y = torch.tensor([4,5,6],dtype=torch.float32)
torch.dot(x,y)

tensor(15.)

In [50]:
A = torch.ones(3,3)
A@x

tensor([3., 3., 3.])

In [55]:
x.reshape(3,1)
torch.mv(A,x)


tensor([3., 3., 3.])

In [69]:
y = y.reshape(3,1)

In [71]:
torch.mm(A,y)

tensor([[15.],
        [15.],
        [15.]])

In [76]:
A = torch.arange(9,dtype=torch.float32).reshape(3,3)
y = torch.ones(3)
torch.mv(A,y)

tensor([ 3., 12., 21.])

In [77]:
torch.norm(A)

tensor(14.2829)

In [81]:
A = torch.arange(12, dtype=torch.float32).reshape(3,4)
x = torch.ones(4)
y = torch.ones(3)
z = torch.ones(4).reshape(4,1)
A@x, torch.mv(A,x), torch.mv(A.T, y),torch.mm(A,z)

(tensor([ 6., 22., 38.]),
 tensor([ 6., 22., 38.]),
 tensor([12., 15., 18., 21.]),
 tensor([[ 6.],
         [22.],
         [38.]]))